### ISSUE TITLE
Update Day-12

### ISSUE THREAD

**Issue by SHIVANGISINGH1** [DeCodeCafe/OpenSource-Cafe#10]
**Guest Name:** **Janvi Thakkar**

**Work to Do:** Please share the content of the meeting here. Also if in the future you would like to write about it in your blog, share it with us here.

**Issue Link:** https://github.com/DeCodeCafe/OpenSource-Cafe/issues/10

**Comment by Rahulkhinchi03** [comment]
@SHIVANGISINGH1 Please write a PR description in a format to make others understand about your issue.
Using words like please and kindly will be highly appreciated.

Eg:

Guest Name:
Work to Do:
Issue Link:

**Comment by SHIVANGISINGH1** [comment]
> @SHIVANGISINGH1 Please write a PR description in a format to make others understand about your issue. Using words like please and kindly will be highly appreciated.
> 
> Eg:
> 
> Guest Name: Work to Do: Issue Link:


Okay, so I need to write a PR description here in this issue for the guest right?

**Comment by Rahulkhinchi03** [comment]
You have to do it here

**Comment by SHIVANGISINGH1** [comment]
> You have to do it here

I am not sure how to write the description. Have a look at this, if you have some specific template you can share I will edit it asap. 


**Guest Name**: Janvi Thakkar

**Work to Do**: Please share the content of the meeting here. Also if in the future you would like to write about it in your blog, share it with us here.

**Issue Link**:  https://github.com/DeCodeCafe/OpenSource-Cafe/issues/10

**Comment by Rahulkhinchi03** [comment]
@SHIVANGISINGH1 This is what I was talking about. Please update the content :-)
