### ISSUE TITLE
Update for podcast (5th june) - Fossology

### ISSUE THREAD

**Issue by rishabh0906** [DeCodeCafe/OpenSource-Cafe#12]
Please add your introduction and links to your socials. Also, in the future, if you write a blog on your journey then you can share the link in the file.
The schedule of the meeting can be found [here](https://github.com/DeCodeCafe/OpenSource-Cafe/blob/main/Schedule.md#date-12th-june-2022).

**Comment by Rahulkhinchi03** [comment]
@rishabh0906  Please write a PR description in a format to make others understand about your issue.

Eg:
Guest Name:
Work to Do:
Issue Link:
